services:
  chronotrack-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chronotrack-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - chronotrack
    depends_on:
      - mysql
    ports:
      - "8000:8000"

  mysql:
    image: mysql:8.0
    container_name: chronotrack-mysql
    restart: unless-stopped
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chronotrack
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - chronotrack
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10

  adminer:
    image: adminer
    container_name: chronotrack-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - chronotrack

networks:
  chronotrack:
    driver: bridge
volumes:
  dbdata:
