version: '3.8'

services:
  chronotrack-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chronotrack-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - chronotrack
    depends_on:
      - mysql
    ports:
      - "8000:8000"  # Laravel app exposed on localhost:8000
    environment:
      - DB_HOST=mysql
      - DB_PORT=3310
      - DB_DATABASE=chronotrack
      - DB_USERNAME=root
      - DB_PASSWORD=root

  mysql:
    image: mysql:8.0
    container_name: chronotrack-mysql
    restart: unless-stopped
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chronotrack
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - chronotrack
  adminer:
    image: adminer
    container_name: chronotrack-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - chronotrack

networks:
  chronotrack:

volumes:
  dbdata:
